### ISSUE TITLE
Error creating visualization

### ISSUE THREAD

**Issue by dersteppenwolf** [gkudos/qgis-cartodb#28]
os linux
layers: world borders, japan buildings osm

Ha ocurrido un error mientras se ejecutaba el código de Python:

Traceback (most recent call last):
  File "/home/juanmendez/.qgis2/python/plugins/QgisCartoDB/dialogs/CreateViz.py", line 142, in cbCreateViz
    cartoDBApi.getLayersMap(data['map_id'])
KeyError: 'map_id'

Versión de Python:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

Versión de QGIS:
2.8.0-Wien Wien, exported

Ruta de Python: ['/usr/share/qgis/python/plugins/processing', '/usr/share/qgis/python', u'/home/juanmendez/.qgis2/python', u'/home/juanmendez/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/feedparser-5.1.3-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/xlrd-0.9.3-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/juanmendez/.qgis2//python', '/usr/share/qgis/python/plugins/fTools/tools']

**Comment by elesdoar** [comment]
Duplicate #25
