### ISSUE TITLE
not able to connect to QGIS

### ISSUE THREAD

**Issue by seferg** [gkudos/qgis-cartodb#32]
any idea as to why my CartoDB account isn't connect using the QGIS plugin?  I have a paid account (not enterprise) but no luck.

**Comment by elesdoar** [comment]
Please check if user and api key are correct.

**Comment by seferg** [comment]
Thanks Michael.. I tried entering my userID and API key several times
without success.
Any other thoughts?  I have QGIS 2.8.1 installed.

**Comment by elesdoar** [comment]
Please  try reinstalling the plugin.

Could you send a screenshot, please.

**Comment by seferg** [comment]
the only error message i'm getting is here.  I tried re-installing the
plugin and received this.  I have own two CartoDB accounts (personal and
organizational) neither one seems to work.

[image: Inline image 1]

**Comment by elesdoar** [comment]
Hi @seferg 

This error still occur?

**Comment by seferg** [comment]
Hi -

i was able to make the connection work in QGIS...thanks!

Scott

**Comment by elesdoar** [comment]
I'm closing this issue, but, did you do something?

**Comment by seferg** [comment]
i think my company firewall was causing the issue...once i tried connecting
from home and no problem.

**Comment by dersteppenwolf** [comment]
HI.
Sometimes corporate firewalls are too restrictive.

Thanks for your comments
