### ISSUE TITLE
Error updating recently uploaded data

### ISSUE THREAD

**Issue by elesdoar** [gkudos/qgis-cartodb#33]
Upgrade cartodb-postgresql extension to 0.9.4 from new CartoDB release, which includes the new cartodbfy process. New user tables won't have the columns created_at nor updated_at.

https://github.com/CartoDB/cartodb/releases/tag/v3.11.0
https://github.com/CartoDB/cartodb-postgresql/blob/0.9.4/NEWS.md#090-2015-08-19

This generates an error creating new features from qgis-cartodb plugin, those columns are expected from the plugin.

@javisantana @andrewxhill

**Comment by javisantana** [comment]
you can create them in the same way other columns exists. The trigger to update updated_at column is still there, you just need to execute:

```
ALTER TABLE YOURTABLE ADD created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE YOURTABLE ADD updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
CREATE trigger update_updated_at_trigger BEFORE UPDATE ON YOURTABLE FOR EACH ROW EXECUTE PROCEDURE public._CDB_update_updated_at()
```

Those columns were taking lot of space and not so many people were using them.

Why do you need them?

**Comment by elesdoar** [comment]
No, these are not necessary though they used to be required fields and not nullable in the exported sqlite file.
Does old tables exporting still generate created_at and updated_at as not nullable fields?

**Comment by javisantana** [comment]
Yes, old tables still have those columns
