### ISSUE TITLE
Manual Install - Missing metadata

### ISSUE THREAD

**Issue by dersteppenwolf** [gkudos/qgis-cartodb#36]
I manually installed the plugin per the instructions here:

{https://github.com/gkudos/qgis-cartodb/wiki/Install}

Upon opening QGIS, I get the error message:

This plugin is broken
Missing metadata file

I have installed it here: C:\Program Files\QGIS Pisa\apps\qgis\python\plugins

**Comment by dersteppenwolf** [comment]
For manual installation, the files should be copied to 
C:\Users\[user name]\.qgis2\python\plugins

( C:\Program Files\ causes OS permission problems )

**Comment by elesdoar** [comment]
Or grant write permissions for `C:\Program Files\QGIS Pisa\apps\qgis\python\plugins\QGISCartoDB` folder.
