### ISSUE TITLE
QgisCartoDB toolbox doesn't appear after installation

### ISSUE THREAD

**Issue by jonniedeb** [gkudos/qgis-cartodb#37]
I cannot connect to cartoDB from within QGIS since the toolbox is absent, which means I can't add a new connection. When I try accessing the plugin from the menu (Internet > Carto DB Plugin), all the items are greyed out.

I tried reinstalling the plugin several times, but it doesn't solve the issue.

I use QGIS 2.8.2-Wien on Windows 8.1 x64.
The installation log says: "GDAL Version: 1110200  SQLite driver is found"

Thank you for any help you could bring!

**Comment by dersteppenwolf** [comment]
Looks like a problem of qgis.  Could you try a newer version? (2.8.3.1  or  2.10.1.1 )

**Comment by jonniedeb** [comment]
I've installed QGIS 2.10.1, and the problem remains.
I thought it might due to a conflict with other extensions, so I deactivated all the extensions which were not from the base installation. And it doesn't solve the issue either...

**Comment by elesdoar** [comment]
Please check if web toolbar is activated.

Go to menu: View -> Toolbars -> Web

**Comment by jonniedeb** [comment]
Thank you ;) it solved it

**Comment by elesdoar** [comment]
:+1:
