### ISSUE TITLE
Import tool for data visualization (qgis->cartodb)

### ISSUE THREAD

**Issue by Stinkender** [gkudos/qgis-cartodb#38]
It would be nice if the qgis-cartodb plugin could also import my data visualization to CartoDB. I mentioned this in my tweet earlier, found here: https://twitter.com/AlsuhailFaris/status/660025811957915648

**Comment by dersteppenwolf** [comment]
It is possible 
https://github.com/gkudos/qgis-cartodb/wiki/Publish-single-or-multilayer-visualizations
