### ISSUE TITLE
Any plans to support CartoDB installations not hosted on cartodb.com?

### ISSUE THREAD

**Issue by azvoleff** [gkudos/qgis-cartodb#39]
From a brief look at the code it looks like there are a few places in the plugin where cartodb.com is hard-coded as the host. Do you have any plans for adding the hostname as an option in the qGIS GUI? Or would you be open to patches adding this?

**Comment by elesdoar** [comment]
Hello, not for now, but you could fork this project.

API class accepts other host as constructor parameter.
https://github.com/gkudos/qgis-cartodb/blob/master/cartodb/cartodbapi.py#L19

You could modify API call adding a last parameter with a different host.
https://github.com/gkudos/qgis-cartodb/blob/master/toolbars/CartoDBToolbar.py#L70-L73

**Comment by azvoleff** [comment]
Thanks - I might take a look at this in the future if I have time. Would be great to be able to connect to a self-hosted installation.
