### ISSUE TITLE
error when the layer name contains non-ascii characters

### ISSUE THREAD

**Issue by mgacc0** [gkudos/qgis-cartodb#40]
When trying to upload to CartoDB a QGIS layer with non-ascii characters (for example: a layer called "A Coruña"),
an error occurs:

    File "C:/Users/usuario/.qgis2/python/plugins\QgisCartoDB\dialogs\Upload.py", line 69, in __init__
    qDebug('Layer id {}'.format(id_ly))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 6: ordinal not in range(128)

I don't know if it would be possible to use Unicode strings for the layer names.
Or, at least, the plugin could try to transcode (from Unicode to ASCII)?

**Comment by elesdoar** [comment]
Fixed in code, at next release it will fix in QGIS repositories
