### ISSUE TITLE
Possible to copy QGIS polygon geometry to a carto layer ?

### ISSUE THREAD

**Issue by minskmaz** [gkudos/qgis-cartodb#41]
I haven't been able to find a way but that doesn't mean there isn't. Any suggestions ?

**Comment by dersteppenwolf** [comment]
Did you try to edit the cartodb layer and copy the polygon in it?  (it should work, as normal qgis editing allows it)

**Comment by minskmaz** [comment]
That didn't work for me. Would be great to see a screencast of it. I
haven't been able to find one of copying polygon geometry to different
layers. Nothing in the menus indicates it's possible either.

**Comment by dersteppenwolf** [comment]
http://gis.stackexchange.com/questions/15259/how-to-select-and-copy-a-group-of-polygons-in-qgis
