### ISSUE TITLE
Connect QGISPlugin to custom domain cartodb

### ISSUE THREAD

**Issue by icetorm** [gkudos/qgis-cartodb#46]
Hi gkudos,
Could you help me to solve how connect your plugin to a custom domain created by me of CARTO.
I don't achieve to make it work editing your python files to redirect it to my carto server.

Thanks for your time

**Comment by elesdoar** [comment]
Please, check:

https://github.com/gkudos/qgis-cartodb/blob/master/cartodb/cartodbapi.py#L19

You can fork this project and change:

```python
def __init__(self, cartodbUser, apiKey, multiuser=False, hostname='carto.com')
``` 
for:
```python
def __init__(self, cartodbUser, apiKey, multiuser=False, hostname='mydomain.com')
```
