### ISSUE TITLE
CartoDB to CARTO API entry points

### ISSUE THREAD

**Issue by jsanz** [gkudos/qgis-cartodb#47]
Please update the plugin to use `carto.com` domain instead of `cartodb.com` as new users don't have both enabled so the plugin is not working for them. In any case the `cartodb.com` domain will be removed at some point in the future.

**Comment by elesdoar** [comment]
Last update change entry point to carto.com domain, please check version [0.2.5](https://github.com/gkudos/qgis-cartodb/releases/tag/v0.2.5), however forgot to change some lines, this will be resolved soon.

Thanks for reporting

**Comment by elesdoar** [comment]
Duplicates #44

**Comment by elesdoar** [comment]
I've created a new user and tested this Carto plugin, but it's working correctly. Please update to last version.

**Comment by jsanz** [comment]
awesome @elesdoar tested and working :rocket: 

thank you very much!!
