### ISSUE TITLE
CartoDB plugin is not compatible with QGIS 3 Girona ? 

### ISSUE THREAD

**Issue by capan** [gkudos/qgis-cartodb#56]
CartoDB plugin couldn't be found in plug-in list. So I've tried manuel installation but QGIS gave me the error below;
"This plugin is not compatible with this version of QGIS
The plugin is designed for QGIS 2.4 - 2.99"

**Comment by dersteppenwolf** [comment]
No, it is not compatible: 
https://gisforthought.com/updating-a-plugin-from-qgis-2-to-qgis-3/

Also, the latests versions of Carto need to activate a "Carto Engine" account to have access to api keys:
https://carto.com/docs/carto-editor/your-account/#api-key

**Comment by meerestier** [comment]
Will you update this plugin? Would be a great addition…

**Comment by dersteppenwolf** [comment]
> Will you update this plugin? Would be a great addition…

Sadly it is not possible.

**Comment by meerestier** [comment]
What does it mean, not possible… Is it a matter of resources or technical?

**Comment by dersteppenwolf** [comment]
resources, 
the plugin for qgis3.x must be written from scratch..
and probably it is not feasible according to the new licensing model of carto (engine)
