### ISSUE TITLE
Manage custom URL pointing to a own instance of cartodb

### ISSUE THREAD

**Issue by amnesic** [gkudos/qgis-cartodb#7]
Inside the CartoDB Connection dialog box :
Add to the "CartoDB User", "Carto DB Api Key" field an advanced mode to be able to use a custom URL field. (eg. https://yourowninstance.org)

It could be a nice enhancement.

**Comment by elesdoar** [comment]
Thanks,

But it would not be planned for future releases, we try to only support the official cloud services of Cartodb.
